services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./backend/.env.test

  node:
    container_name: node
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - ./backend/.env.test